image: "python:3.7-slim-stretch"

cache:
  key: build-cache
  untracked: true
  paths:
    - dist/

before_script:
  - python --version

stages:
- build
- deploy

build:
  stage: build
  script:
    - python3 -m pip install --upgrade pip setuptools wheel
    - python3 setup.py sdist bdist_wheel
    - python3 -m pip install --upgrade twine
    - python3 twine check dist/*
    - echo quit | openssl s_client -showcerts -servername cencoreg.cencosud.corp -connect cencoreg.cencosud.corp:5000 > cacert.pem
    - export PIP_CERT=`pwd`/cacert.pem
    - python3 -m twine upload --repository-url https://cencoreg.cencosud.corp/repository/pyprod/ dist/* --cert $PIP_CERT --username $NEXUS_USER --password $NEXUS_PWD

develop:
  stage: deploy
  only:
    - develop
  script:
    - echo Done
