image: "python:3.7-slim-stretch"

before_script:
  - python --version

stages:
- build
- deploy

build:
#  image: python:3.7-slim-stretch
  stage: build
  script:
    - python3 -m pip install --upgrade pip setuptools wheel
    - python3 setup.py sdist bdist_wheel

develop:
  stage: deploy
  only:
    - develop
#  image: python:3.7-slim-stretch
  variables:
    PIP_CERT: CERT
  script:
    - echo quit | openssl s_client -showcerts -servername cencoreg.cencosud.corp -connect cencoreg.cencosud.corp:5000 > cacert.pem
    - export PIP_CERT=`pwd`/cacert.pem
    - python3 -m twine upload --repository-url https://cencoreg.cencosud.corp/repository/pyprod/ dist/* --cert $PIP_CERT --verbose
